### ISSUE TITLE
Move Repo to github organization

### ISSUE THREAD

**Issue by kenodressel** [quarantine-hero/quarantine-hero#58]
Postponed until next week

**Comment by florianschmidt1994** [comment]
This was two weeks ago. @kenodressel are we still thinking of this? If yes, I was thinking maybe we could start by moving the repo to an organization, but keeping the deployment to GH pages of `kenodressel/quarantine-hero` so that we don't have to set up the CNAME stuff and GH pages for the new repo

**Comment by kenodressel** [comment]
yeah could be a transitional solution for example

**Comment by tgraupne** [comment]
Hi @florianschmidt1994, this does sound like a great idea. How would this deployment look like? Would the GitHub action in the new org and repository get some API key to write to @kenodressel's repository?

**Comment by kenodressel** [comment]
I think we should just change the cname/a record on the domain and completly host it in the new repo

**Comment by kenodressel** [comment]
Steps:
- transfer ownership to QH Orga
- fork repo back to kenodressel/quarantine-hero
- update domain cname to QH Orga

**Comment by kenodressel** [comment]
We since made some changes to our DNS setup and the transition should be significant smoother now. We should be good after transferring owner ship. This could lead to some minor outages for a couple of minutes but its not a major concern anymore.
