### ISSUE TITLE
Add functionality to remove email addresses (users) from QH

### ISSUE THREAD

**Issue by kenodressel** [quarantine-hero/quarantine-hero#62]
Problem: Firebase is non relational so we need to scan the whole database for these records.

**Comment by tgraupne** [comment]
Use cases:

- admin dashboard
- user deletes itself

**Comment by florianschmidt1994** [comment]
Some things that come to my mind:

- when giving some users access to this dashboard they will be using a token with admin privileges. We need to make sure that this token is limited in what it can do in order to not give too much access to things
- we need a way to store this token, as this will probably be embedded in a client-side admin SDK. We need to make sure not to leak an admin token in the process

**Comment by Maurice22** [comment]
I created a frontend and backend functionality for this. Currently I'm blocked due to the fact that we have our /offer-help collection and the /ask-for-help/offer-help collection. This makes it impossible to query all subcollections. Hence, we would need to do a migration from /offer-help to i.e. /notifications. An idea to do this would be to do an export and import using the google cloud console.

**Comment by Maurice22** [comment]
TODOs for goLive:
- [] Do migration from /offer-help to /notifications on prod
- [] Align security rules on prod (i.e. rename /offer-help rule to /notifications
- [] Add group query index to all /xyz/offer-help collections on prod
